use_frameworks!

target 'YangNavigationHelper_Example' do
  pod 'YangNavigationHelper', :path => '../'
  pod 'SnapKit'

  target 'YangNavigationHelper_Tests' do
    inherit! :search_paths
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    
  end
end
